<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="..\HomeKTV.Core\HomeKTV.Core.csproj" /></ItemGroup>

</Project>
