<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HomeKTV.Core\HomeKTV.Core.csproj" />
    <ProjectReference Include="..\HomeKTV.Library\HomeKTV.Library.csproj" />
    <ProjectReference Include="..\HomeKTV.Lyrics\HomeKTV.Lyrics.csproj" />
  </ItemGroup>

</Project>
